media:
    input: public/assets
    output: ../../../public/assets

content:
  - name: general
    label: General
    path: src/content/general
    type: collection
    view:
      - fields: [title, date]
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: body, label: Body, type: rich-text }
  - name: news
    label: News
    path: src/content/news
    type: collection
    fields:
      - { name: title, label: Title, type: string }
      - { name: thumbnail, label: Thumbnail, type: image }
      - { name: date, label: Date, type: date }
      - { name: description, label: Description, type: string }
      - { name: tags, label: Tags, type: string, list: { min: 0, max: 5 }}
      - { name: draft, label: Draft, type: boolean }
      - { name: body, label: Body, type: rich-text }
  - name: updates
    label: Updates
    path: src/content/updates
    type: collection
    fields:
      - { name: title, label: Title, type: string }
      - { name: thumbnail, label: Thumbnail, type: image }
      - { name: date, label: Date, type: date }
      - { name: location, label: Location, type: string }
      - { name: description, label: Description, type: string }
      - { name: tags, label: Tags, type: string, list: { min: 0, max: 5 }}
      - { name: draft, label: Draft, type: boolean }
      - { name: body, label: Body, type: rich-text }
    