version: '3.9'

services:
  astro:
    build: .
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting node_modules inside container
    command: npm run dev
