export const SUBTEAMS = [
    { label: 'mech', 
        name: 'Mechanical Subteam', 
        img: '/assets/subteams/mechanical.jpeg'},
    { label: 'elec', 
        name: 'Electrical Subteam', 
        img: '/assets/subteams/electrical.png'},
    { label: 'software', 
        name: 'Software Subteam', 
        img: '/assets/subteams/software.png'},
    { label: 'biochem', 
        name: 'Biochemical Subteam', 
        img: '/assets/subteams/biochem.jpeg'},
    { label: 'business', 
        name: 'Business Subteam', 
        img: '/assets/subteams/business.jpeg'},
]